name: API Testing Workflow
'on':
  - push
  - workflow_dispatch
jobs:
  test-runner:
    runs-on: ubuntu-latest
    env:
      API_URL: 'https://pokeapi.co/api/v2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint --quiet
      - name: Run tests and generate report
        env:
          TEST_REPORT_PATH: report.xml
        run: npm test -- --reporter=mocha-junit-reporter --reporter-options mochaFile=./test-results.xml
      - name: Upload test report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./test-results.xml
  test-docker:
    runs-on: ubuntu-latest
    env:
      API_URL: 'https://pokeapi.co/api/v2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
      - name: Build and run Docker Compose
        run: docker-compose up -d