name: API Testing Workflow
'on':
  - push
  - workflow_dispatch
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests and generate report
        env:
          TEST_REPORT_PATH: report.xml
        run: >-
          npm test -- --reporter=mocha-junit-reporter --reporter-options
          mochaFile=./test-results.xml
      - name: Upload test report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./test-results.xml
