name: API Testing Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_URL: https://pokeapi.co/api/v2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint --quiet

      - name: Run tests and generate report
        env:
          TEST_REPORT_PATH: report.xml
        run: |
          npm test -- --reporter=mocha-junit-reporter

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./test-results.xml

      - name: Display JUnit Report
        uses: phoenix-actions/test-reporting@v8
        id: junit-reports
        with:
          name: WebdriverIO Junit Reports
          path: ./test-results.xml
          reporter: jest-junit
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: false
