name: Daily API Tests

on:
  schedule:
    - cron: '0 10 * * 1-5'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    - name: Run tests and generate report
      env:
         TEST_REPORT_PATH: report.xml
      run: |
         npm test -- --reporter=mocha-junit-reporter --reporter-options mochaFile=./test-results.xml

    - name: Upload test report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Test Report
        path: ./test-results.xml
